name: Contenedor Tarea 8

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip install requests pandas  # Instala las dependencias necesarias

      - name: Create Python Script
        run: |
          echo "import pandas as pd" > script.py
          echo "data = {'Nombre': ['Juan', 'Alonso'], 'Edad': [21, 20]}" >> script.py
          echo "df = pd.DataFrame(data)" >> script.py
          echo "print(df)" >> script.py

      - name: Run Python Script
        run: |
          python script.py > output.txt

      - name: Upload Script Output
        uses: actions/upload-artifact@v3
        with:
          name: python-output
          path: output.txt